name: Prueba técnica NttData

on:
  push:
    branches: [ master ]
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: awssession
        role-to-assume: ${{secrets.AWS_IAM_ROLE}}
        aws-region: ${{secrets.AWS_REGION}}
    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -var "access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var "region=${{ secrets.AWS_REGION }}"

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      working-directory: terraform
      run: terraform apply -auto-approve -var "access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var "region=${{ secrets.AWS_REGION }}"